##################################################
# This file auto generated by preform, do not edit!
# Instead edit 
# /Users/aaroncollins/Development/kraken/iac/projects/infra/state.tf.tpl
##################################################


terraform {
  backend "s3" {
    bucket  = "krakops-iac"
    key     = "infra/us-west-1/dev"
    region  = "us-west-1"
    encrypt = true
  }
}
provider "aws" {
  region = "us-west-1"
}

