##################################################
# This file auto generated by preform, do not edit!
# Instead edit 
# /Users/aaroncollins/Development/kraken/iac/projects/infra/secrets.tf.tpl
##################################################





# Swimlane: devops, Service: litecoin-node, SecretName: password
resource "aws_ssm_parameter" "devops_litecoin-node_password" {
  name      = "/${var.vpc_name}/devops/litecoin-node/litecoin-node/v1/password"
  overwrite = true
  type      = "SecureString"
  value     = "jlqNkYQIgo"

  tags = merge(
    local.common_tags,
    {
      "client_name"  = "devops"
      "cluster_name" = "${var.vpc_name}-devops"
      "Name"         = "password"
      "Service"      = "litecoin-node"
    },
  )
}



# Swimlane: devops, Service: litecoin-node, SecretName: username
resource "aws_ssm_parameter" "devops_litecoin-node_username" {
  name      = "/${var.vpc_name}/devops/litecoin-node/litecoin-node/v1/username"
  overwrite = true
  type      = "SecureString"
  value     = "analogrithems"

  tags = merge(
    local.common_tags,
    {
      "client_name"  = "devops"
      "cluster_name" = "${var.vpc_name}-devops"
      "Name"         = "username"
      "Service"      = "litecoin-node"
    },
  )
}




